### ISSUE TITLE
using template coverage task has errors

### ISSUE THREAD

**Issue by null-prophet** [wighawag/template-ethereum-contracts#1]
Hi there, I came across and started prototyping a project using this amazing template and the hardhat-deploy plugin against BSC and have a strange error when running the `yarn coverage` task.

In the tests I rely on the typechain code but it doesn't seem like the coverage task is starting up the local testnet and deploying the contracts.

normally when I run `yarn test` I see the deploy happening (I have a few console logs in a block in the deploy to show I got the dependent contracts address etc).

```
❯ yarn test
yarn run v1.22.10
$ cross-env HARDHAT_DEPLOY_FIXTURE=true HARDHAT_COMPILE=true mocha --bail --recursive test

  SimpleBEP20 - Coiny1
Nothing to compile
No need to generate any newer typings.
Found TT token at address: 0xa675CE53FCFf9ee8e61b3dFf275210E859C0b623
    ✔ transfer fails - non hodler to rando 1 (1417ms)
    ✔ transfer succeed from deployer to rando 1

  TTContract
    ✔ TTContract Setup Correctly.
    ✔ will ensure I have the correct holding Requirement
    ✔ Can Lock Coins - And Unlock in the future.

  TTToken
    ✔ transfer fails - non hodler to rando 1
    ✔ transfer succeed from deployer to rando 1


  7 passing (2s)

✨  Done in 6.77s.
```

so you see just after running the first test `  SimpleBEP20 - Coiny1` there is some debug from the deploy script.

Running coverage however:

```
❯ yarn coverage
yarn run v1.22.10
$ cross-env HARDHAT_DEPLOY_FIXTURE=true hardhat coverage

Version
=======
> solidity-coverage: v0.7.16

Instrumenting for coverage...
=============================

> contract list...

Compilation:
============

Compiling 12 files with 0.8.4
Generating typings for: 16 artifacts in dir: typechain for target: ethers-v5
Successfully generated 30 typings!
Compilation finished successfully

Network Info
============
> HardhatEVM: v2.4.1
> network:    hardhat

Nothing to compile
No need to generate any newer typings.

 < FAILING TESTS>

  0 passing (35ms)
  7 failing

  1) SimpleBEP20 - Coiny1
       transfer fails - non hodler to rando 1:
     Error: No Contract deployed with name BEP20Coiny1
      at Object.getContract (node_modules/@nomiclabs/hardhat-ethers/src/internal/helpers.ts:444:11)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)

  <ALL ERRORS IDENTICAL>

> Istanbul reports written to ./coverage/ and ./coverage.json
Error in plugin solidity-coverage: ❌ 7 test(s) failed under coverage.

For more info run Hardhat with --show-stack-traces
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The yarn task is fine, no changes, and I can't see what the issue would be, it's not a deal breaker. Just puzzled whats not working and why.

I am using solc 0.8.4

and devDepenencies are:

```
  "devDependencies": {
    "@nomiclabs/hardhat-ethers": "npm:hardhat-deploy-ethers@0.3.0-beta.10",
    "@openzeppelin/contracts": "^4.2.0",
    "@typechain/ethers-v5": "^7.0.1",
    "@typechain/hardhat": "^2.1.1",
    "@types/chai": "^4.2.19",
    "@types/mocha": "^8.2.2",
    "@types/node": "^15.12.2",
    "@typescript-eslint/eslint-plugin": "^4.28.1",
    "@typescript-eslint/parser": "^4.28.1",
    "chai": "^4.3.4",
    "chai-ethers": "^0.0.1",
    "cross-env": "^7.0.3",
    "dotenv": "^10.0.0",
    "eslint": "^7.30.0",
    "eslint-config-prettier": "^8.3.0",
    "ethers": "^5.4.1",
    "fs-extra": "^10.0.0",
    "hardhat": "^2.4.1",
    "hardhat-deploy": "^0.8.9",
    "hardhat-gas-reporter": "^1.0.4",
    "mocha": "^9.0.1",
    "prettier": "^2.3.2",
    "prettier-plugin-solidity": "^1.0.0-beta.13",
    "solhint": "^3.3.6",
    "solhint-plugin-prettier": "^0.0.5",
    "solidity-coverage": "^0.7.16",
    "ts-generator": "^0.1.1",
    "ts-node": "^10.0.0",
    "typechain": "^5.1.1",
    "typescript": "^4.3.5"
  }
```

If you need more info to debug the issue let me know, thought this stuff would be the most relevant.

Thanks so much for sharing an amazing set of templates and tools, really enjoying using them!

**Comment by wighawag** [comment]
Thanks for the report, See the following comment : https://github.com/wighawag/hardhat-deploy/issues/132#issuecomment-875365555

I ll close the issue once this is resolved somehow

**Comment by null-prophet** [comment]
Thank you! I had seen some comments on there but wasn't sure what was still a problem, what was resolved  or what I had borked!

**Comment by wighawag** [comment]
I pushed a fix for it via patch-package. like this we do not need to wait for solidity-coverage to get fixed
